name: Build ldns

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout bucket
        uses: actions/checkout@v5
        with:
          path: bucket

      - name: Checkout ldns
        uses: actions/checkout@v5
        with:
          repository: NLnetLabs/ldns
          path: ldns
          ref: develop
          fetch-depth: 0

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-{toolchain,autotools,openssl}

      # - name: Setup upterm session
      #   uses: owenthereal/action-upterm@v2

      - name: Build ldns
        working-directory: ldns
        run: |
          set -e

          autoreconf -fi

          ./configure \
            --prefix=/usr \
            --with-ssl=/ucrt64

          make -j"$(nproc)"

          rm -rf "$GITHUB_WORKSPACE/staging"

          make DESTDIR="$GITHUB_WORKSPACE/staging" install
