name: build ldns
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'bucket/ldns.json'
jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout home repository
        uses: actions/checkout@v4

      - name: Checkout ldns repository
        uses: actions/checkout@v4
        with:
          repository: NLnetLabs/ldns
          path: ldns

      - name: Install MinGW and Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mingw-w64 \
            autoconf \
            automake \
            libtool \
            bison \
            flex \
            make

      # - name: Setup warpbuild session
      #   uses: uses: Warpbuilds/action-debugger@v1.3

      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
        with:
          wait-timeout-minutes: 5
          limit-access-to-actor: true

      - name: Run Windows Build Script
        run: |
          cd ldns
          curl -L https://www.openssl.org/source/openssl-3.5.3.tar.gz -o ./openssl-3.5.3.tar.gz
          chmod +x makewin.sh
          export GITREPO=$(pwd)
          ./makewin.sh -wssl=./openssl-3.5.3.tar.gz

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ldns-windows-binaries
          path: "*.zip"
